#!/bin/sh

# Display current network utilization by process, connection and remote IP/hostname 
cargo install bandwhich

# A cat(1) clone with wings.
cargo install bat

# A cross-platform graphical process/system monitor with a customizable interface and a multitude of features. Supports Linux, macOS, and Windows.
cargo install bottom

# Generate a Zeal/Dash docset for your rust package.
cargo install cargo-docset

# fd is a simple, fast and user-friendly alternative to find.
cargo install fd-find

# Faster workspace management.
cargo install fw

# blazing fast terminal-ui for git.
cargo install gitui

# Fast, lag-free terminal file browser
cargo install hunter

# JSON query language CLI tool.
cargo install jql

# Fast indexing and querying your filesystem. Replaces locate / mlocate / updatedb.
cargo install lolcate-rs

# ls command with a lot of pretty colors and some other stuff.
cargo install lsd

# cat for markdown: Show markdown documents in terminals.
cargo install mdcat

# Monitor that network is reachable; in case of failure, run a command.
cargo install pingkeeper

# modern replacement for ps.
cargo install procs

# Project management CLI for git repos
cargo install projector

# ripgrep is a line-oriented search tool that recursively searches your current directory for a regex pattern while respecting your gitignore rules.
cargo install ripgrep

# An intuitive find & replace CLI.
cargo install sd

# Shared Compilation Cache.
cargo install sccache

# Fast minimal infinitely customizable prompt for any shell.
cargo install starship

# Fetch and show tldr help pages for many CLI commands. Full featured offline client with caching support. .
cargo install tealdeer

# Watch files for modifications then execute commands.
cargo install watchexec

# A faster way to navigate your filesystem.
cargo install zoxide
